environment:
  name: "Humanoid-v5"
  max_episode_steps: 1000
  render_mode: null

model:
  skill_dim: 8         # paper uses 8 for Humanoid
  repr_dim: 8
  hidden_dim: 1024

training:
  total_timesteps: 1000000
  lr: 0.0001
  gamma: 0.99
  tau: 0.005
  xi: 5.0
  batch_size: 256
  buffer_size: 1000000
  phi_l2_reg: 0.001

logging:
  log_interval: 5000
  eval_interval: 50000
  save_interval: 10000

paths:
  save_dir: "./experiments/humanoid_gym_csf"
  log_dir: "./logs/humanoid_gym_csf"

zeroshot:
  num_episodes: 50
  max_steps: 1000
  goal_sampling_range: [-10.0, 10.0]   # per paper's Appendix B.4
  goal_threshold: 1.0

hrl:
  downstream_env: "HumanoidGoal-v0"    # if available; else remove HRL section
  total_episodes: 1000
  meta_policy_lr: 0.0001
  option_timesteps: 25
  hrl_batch_size: 256
  hrl_buffer_size: 100000
